version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - '4000:4000'
    volumes:
      - /api:/app
      - /app/node_modules
  frontend:
    build: ./gui
    container_name: gui_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

# docker run --name myapp_nodemon -p 4000:4000 --rm -v /home/rishi/devspace/dockerlearn:/app -v /app/node_modules myapp:nodemon