version: "3.8"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - '4000:4000'
    expose:
      - '4000'
  frontend:
    build: ./gui
    container_name: gui
    ports:
      - '3000:3000'
    expose:
      - '3000'
    stdin_open: true
    tty: true
